### PR TITLE
Use YlGnBu colormap (reversed) for salinity by default

### PR DESCRIPTION
**Pull request by kjordahl**
Instead of using jet, let's use YlGnBu for the salinity colormap.

Reference: https://www.youtube.com/watch?v=XjHzLUnHeM0 by @kthyng.

### CODE REVIEW

**Comment by kjordahl** [comment]
Screenshot:

screen shot 2015-08-13 at 4 01 51 pm

The contours are a bit coarse, and the logspace levels perhaps not ideal.

**Comment by kthyng** [comment]
Can we use the somewhat updated version of the colormap for salinity found
at matplotlib.org/cmocean?

On Thursday, August 13, 2015, Kelsey Jordahl <notifications@github.com>
wrote:

> Screenshot:
>
> [image: screen shot 2015-08-13 at 4 01 51 pm]
> <https://cloud.githubusercontent.com/assets/499079/9263799/0e2a81c0-41d5-11e5-871b-c6b523642d68.png>
>
> The contours are a bit coarse, and the logspace levels perhaps not ideal.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enthought/tabs/pull/64#issuecomment-130873150>.
>


-- 
Kristen M. Thyng
Assistant Research Scientist
Department of Oceanography
Texas A&M University
Eller O&M 618
http://kristenthyng.com

**Comment by kjordahl** [comment]
> Can we use the somewhat updated version of the colormap for salinity found at matplotlib.org/cmocean?

Sure! I think I'll copy [cm.py](https://github.com/matplotlib/cmocean/blob/master/cmocean/cm.py) to this repo instead of introducing it as a dependency for now.

**Comment by kthyng** [comment]
great!

**Comment by kjordahl** [comment]
I just made cmocean a dependency. If that's a problem we can copy the colormaps as needed.

screen shot 2015-08-14 at 6 16 20 pm

**Comment by kthyng** [comment]
Great! I think it would be good as a dependency in that as other fields are
being plotted for TABS, they can use the appropriate colormaps too. I'll
look into making the package smaller — I just tested downloading it fresh
and it took longer than I expected...

On Fri, Aug 14, 2015 at 6:17 PM, Kelsey Jordahl <notifications@github.com>
wrote:

> I just made cmocean a dependency. If that's a problem we can copy the
> colormaps as needed.
>
> [image: screen shot 2015-08-14 at 6 16 20 pm]
> <https://cloud.githubusercontent.com/assets/499079/9286785/a2da7d44-42b0-11e5-9ce6-54085a3db84f.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/enthought/tabs/pull/64#issuecomment-131276130>.
>



-- 
Kristen M. Thyng
Assistant Research Scientist
Department of Oceanography
Texas A&M University
Eller O&M 618
http://kristenthyng.com

**Pull request merged**
